#!/usr/bin/python3

import schedule
import time
import datetime
import mh_z19
import os

INTERVAL = 5
OUTPUT_DIR = '/home/pi/co2/'

def write_file(filename, outlist):
    file = open(filename, 'w')
    for line in outlist:
        file.write('{}\n'.format(line))
    file.close()

class CO2_Logger:
    def __init__(self):
        self.current = ['' for _ in range(60*60//INTERVAL)]
        self.hour = []

    def get_date_string(self):
        now = datetime.datetime.now()
        return '{}-{}-{}_{}:{}:{}'.format(
            now.year,
            now.month,
            now.day,
            now.hour,
            now.minute,
            now.second)

    def read_sensor(self):
        return mh_z19.read().get('co2', None)

    def update(self):
        now = self.get_date_string()
        co2 = self.read_sensor()
        data = '{} {}'.format(now, co2)
        print(data)
        self.current.pop(0)
        self.current.append(data)
        self.hour.append(data)
        write_file('{}current.txt'.format(OUTPUT_DIR), self.current)

    def write_hourly_log(self):
        now = self.get_date_string()
        write_file('{}{}.txt'.format(OUTPUT_DIR, now), self.hour)
        self.hour = []

def main():
    logger = CO2_Logger()
    schedule.every().hour.at(':00').do(logger.write_hourly_log)
    for i in range(60//INTERVAL):
        tmp = ':{}'.format(str(i*INTERVAL).zfill(2))
        schedule.every().minute.at(tmp).do(logger.update)
    while True:
        schedule.run_pending()
        time.sleep(0.1)

if __name__ == '__main__':
    main()
